### ISSUE TITLE
Compatibility of encryption with CryptoJS

### ISSUE THREAD

**Issue by PavolSvidran** [entronad/crypto-es#10]
Hi, i'm using CryptoJS and I've been thinking about switching to CryptoES, but unfortunately my old encrypted data in CryptoJS can't be decrypted with the same password for CryptoES. 

In my process i used TripleDES, Base64, and main AES function where set options are iv, padding and mode.
For both(CryptoJS, CryptoES) is process and options same.

I dont have passwords, and implement system which use both to swap is a lot of work for a small profit.
Is there some different default, or there is no native way to switch from CryptoJS to CryptoES without data loss (for example because some of named functions returns different results for CryptoES/CryptoJS)?

**Comment by entronad** [comment]
What is your CryptoJS version?
There are some changes about Cryption params between 3.XX to 4.XX of CryptoJS, like: https://github.com/brix/crypto-js/pull/211
CryptoES refers to newest version of CryptoJS, and merged those changes: https://github.com/entronad/crypto-es/blob/master/CHANGELOG.md#123

**Comment by PavolSvidran** [comment]
Version is 4.0.0

**Comment by entronad** [comment]
This issue has been fixed in v2.0.0

The CryptoJS has a very ancient bug that salt param is not passed correctly to all password ciphers. It is fixed in 2021, but I failed to notice that. So they became incompatible. It is fixed in v2.0.0 now.
