### ISSUE TITLE
Cannot read property 'call' of undefined   at AESAlgo.reset (cipher-core.js:458)

### ISSUE THREAD

**Issue by softboy99** [entronad/crypto-es#11]
`import CryptoES from "crypto-es";

/**
 * @word 要加密的内容
 * @keyWord String  服务器随机返回的关键字
 */
export function aesEncrypt(word: string, keyWord: string = "XwKsGlMcdPMEhR1B") {
  var key = CryptoES.enc.Utf8.parse(keyWord);
  var srcs = CryptoES.enc.Utf8.parse(word);
  var encrypted = CryptoES.AES.encrypt(srcs, key, {
    mode: new CryptoES.mode.ECB(),
    padding: CryptoES.pad.Pkcs7,
  });
  return encrypted.toString();
}`

**Comment by entronad** [comment]
请升级到 v1.2.7 并更改：
```
mode: new CryptoES.mode.ECB()  -->  mode: CryptoES.mode ECB
```

**Comment by softboy99** [comment]
Hi,
it's worked, thanks
