### ISSUE TITLE
Crypto-ES examples doesn't compile with VSC / Typescript

### ISSUE THREAD

**Issue by mungbeans2** [entronad/crypto-es#12]
I originally wrote some Javascript code using Crypto-ES and got everything working nicely.However after changing the file extension from .js to .tsx my code no longer compiles - there's a problem being indicated with the use of CryptoES.mode.CBC.

I tried copying/pasting the following example code from the usage section at https://www.npmjs.com/package/crypto-es
and there is the same problem. It says "Type 'typeof CFB' is missing the following properties from type 'BlockCipherMode': mixIn ... Did you mean to use 'new' with this expression?"

  const encrypted = CryptoES.AES.encrypt("Message", "Secret Passphrase", { mode: CryptoES.mode.CFB, padding: CryptoES.pad.AnsiX923 });

How can I proceed to fix the problem?

**Comment by entronad** [comment]
This is caused by our type error in tds that mode should be a class, not an object.
We have fixed it in v1.2.7, Please upgrade and have a retry.

**Comment by mungbeans2** [comment]
Thanks, that worked
