### ISSUE TITLE
yarn couldn't find any versions for that matches "^1.2.7"

### ISSUE THREAD

**Issue by softboy99** [entronad/crypto-es#13]
yarn couldn't find any versions for that matches "^1.2.7"

**Comment by entronad** [comment]
Maybe `yarn cache clean` or `yarn --force` or switch to npm will work.

**Comment by softboy99** [comment]
both tried, but failed, it can only list 1.2.6 or below version in list for selection

**Comment by entronad** [comment]
Try v2.0.0
