### ISSUE TITLE
Wrong typing expected in the hasher for PBKDF2

### ISSUE THREAD

**Issue by 188599** [entronad/crypto-es#14]
Typescript complains, but it works:
```ts
CryptoES.PBKDF2(..., { hasher: CryptoES.algo.SHA1 });
```

Typescript accepts this but it doesn't work:
```ts
CryptoES.PBKDF2(..., { hasher: new CryptoES.algo.SHA1() });
```

I'm guessing the type expected for `hasher` should be something like this:
```ts
new (...args: any) => CryptoES.lib.Hasher;
```

**Comment by entronad** [comment]
The type issues are fixed in v2.0.0
