### ISSUE TITLE
skipLibCheck doesn't appear to be needed

### ISSUE THREAD

**Issue by soyuka** [entronad/crypto-es#15]
Hi, thanks for the fork I want to use it to fix es-related issues (core.js not found warning). 

I was reading the README and it doesn't seem I need to use `skipLibCheck` what was your issue? Should we remove this from the README?

**Comment by entronad** [comment]
It's just a typescript configration suggestion.
You can do whatever if the ts compiler does't complain.

**Comment by entronad** [comment]
All js files have own d.ts now in v2.0.0, this config is no longer needed.
