### ISSUE TITLE
no types

### ISSUE THREAD

**Issue by chase-moskal** [entronad/crypto-es#17]
:wave: hello! thanks for this wonderful library!

i'm running into the problem that typescript complains that no typings are found

```typescript
import {MD5} from "crypto-es/lib/md5.js"
 //               ^^
 // Could not find a declaration file for module
```

crypto-es does not yet appear to have a `tsconfig.json` configured to emit declaration files like "md5.d.ts" alongside each module

a possible solution would be to add a `tsconfig.json` which configures `"declaration": true`

```json
{
  "compilerOptions": {
    "declaration": true
  }
}
```

**Comment by entronad** [comment]
All js files have own d.ts now in v2.0.0.
