### ISSUE TITLE
not working with openssl

### ISSUE THREAD

**Issue by iwater** [entronad/crypto-es#20]
OpenSSL 1.1.1i

openssl enc -aes-256-cbc -in infile -out outfile -pass pass:"Secret Passphrase" -e -base64

Decrypt with CryptoES Got Nothing
CryptoES.AES.decrypt(openSSLEncrypted, "Secret Passphrase");

Decrypt with OpenSSL Works Well
openssl aes-256-cbc -d -in outfile -out outfile.txt -pass pass:"Secret Passphrase"

**Comment by entronad** [comment]
Try v2.0.0, a bug of password cipher is fixed in this version, maybe it will help.
