### ISSUE TITLE
TripleDes / Des encrypt & decrypt result are not same as crypto-js

### ISSUE THREAD

**Issue by tonyfung99** [entronad/crypto-es#22]
`CryptoES.TripleDES.encrypt(DATA, CryptoES.enc.Utf8.parse(KEY), {
        mode: CryptoES.mode.ECB,
        format: CryptoES.format.OpenSSL
    });
`

As title, seems crypto-es is unable to produce the same output in both encrypt and decrypt as crypto-js. The output seems incorrect.

**Comment by brownsugar** [comment]
Same here.
DES decryption got different results, in CryptoJS I got the correct result, in CryptoES I need to split the encrypted HEX string to get the correct result.

With CryptoJS
https://codepen.io/brownsugar/pres/OJjJPYY?editors=0012

With CryptoES
https://codesandbox.io/s/cryptoes-des-decryption-zt4cs

**Comment by akashraj9828** [comment]
@entronad is there any update on this?

**Comment by entronad** [comment]
This issue has been fixed in v2.0.0;

The `blockSize` should be an instance field not a static field so that it can be correctly overridden and called. this matters in ES6 class so the definition should differ from CryptoJS.

This issue only affected TripleDes / Des.
