### ISSUE TITLE
Cannot find declaration file for module 'cryptoES/lib/RC4'

### ISSUE THREAD

**Issue by everlose** [entronad/crypto-es#26]
![image](https://user-images.githubusercontent.com/8710568/148323622-0e179742-876b-4de0-a469-50badae302a2.png)

I found this error in the TS project

I checked `cryptoES/lib`, and there was only one declaration file named "index.d.TS", no RC4, MD5

**Comment by entronad** [comment]
Yes there is only integrated d.ts file now, so only full import is supported in TS now
