### ISSUE TITLE
export all encodings for partial import

### ISSUE THREAD

**Issue by hiradyazdan** [entronad/crypto-es#3]
Is it possible to export all other encodings (specially `enc.Utf8`) so they can be used as partial import and eventually help webpack to exclude all un-imported packages?

**Comment by entronad** [comment]
```
import { Uft8 } from 'crypto-es/lib/core.js'
```
This will only import the core.js which is about 700 lines. I think it's small enough.
Some objects or functions are very simple so they have no individual files. You can look up the index.js to find which file to partially import.
