### ISSUE TITLE
Error in Electron: "Must use import to load ES Module"

### ISSUE THREAD

**Issue by asins** [entronad/crypto-es#30]
I was using Electron to write a native application, but reported an error after introducing crypto-es in the Node layer. In the provided npm package, can you distinguish the following usage methods, such as:

```json
{
  "main": "dist/index.cjs.js",
  "module": "dist/index.esm.js"
}
```

**Comment by entronad** [comment]
Try there configs: https://nodejs.org/dist/latest-v18.x/docs/api/packages.html#determining-module-system
CryptoES is totally esm
