### ISSUE TITLE
Please enable private disclosures ASAP

### ISSUE THREAD

**Issue by Zemnmez** [entronad/crypto-es#39]
You can do it with the [Security panel].

Please enable:

 * "Security advisories"
 * "Private vulnerability reporting"

I found a vulnerability in [crypto-js] that also affects this package. Please enable vulnerability disclosures so I can responsibly disclose the vulnerability. Thanks.

Twitter thread with some context: https://twitter.com/zemnmez/status/1714513369745830026

[Security panel]: https://github.com/Zemnmez/monorepo/security
[crypto-js]: https://github.com/brix/crypto-js

**Comment by entronad** [comment]
As you asked, I have enabled "Security advisories" and "Private vulnerability reporting" of this repo.

**Comment by Zemnmez** [comment]
Thanks!On 18 Oct 2023, at 19:06, LIN Chen ***@***.***> wrote:﻿
As you asked, I have enabled "Security advisories" and "Private vulnerability reporting" of this repo.

**Comment by Zemnmez** [comment]
Might be a day or two before I send the disclosure in. I'm trying to organise a coordinated disclosure.

**Comment by Zemnmez** [comment]
https://github.com/entronad/crypto-es/security/advisories/GHSA-mpj8-q39x-wq5h
