### ISSUE TITLE
[index.d.ts] CipherParams should have optional fields

### ISSUE THREAD

**Issue by AlttiRi** [entronad/crypto-es#4]
[CipherParams](https://github.com/entronad/crypto-es/blob/master/lib/index.d.ts#L500) should have optional fields, not required, like it is for [ `CipherParamsData` in `index.d.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cryptojs/index.d.ts#L132) for _original_ CryptoJS 3.1.2.

I want to directly pass a `WordArray`, but I get the warning from IDE for a code like this:
```js
    CryptoES.AES.decrypt(
        {ciphertext: wordArray},
        key,
        {iv}
    );
```
![warn](https://user-images.githubusercontent.com/16310547/82138441-33e5ca00-9829-11ea-8d1d-218c85f2e1fd.png)

[`decrypt` method](https://github.com/entronad/crypto-es/blob/master/lib/index.d.ts#L936) uses only the `ciphertext` field from the passed `CipherParamsData` (CryptoJS) / `CipherParams` (CryptoES) object.

**Comment by entronad** [comment]
I don't think the first param of decrypt() can be a wordArray.

As is sayed in the "The Cipher Output" in README:
The result of encryp() is a CipherParams, it is the full information of the encryption, not mearly the wordArray. CipherParams has a toString() method to present this object as a string.
So the union type (CipherParams | string) of the first param in decrypt() refers to this object and it's string form, only a wordArray or {ciphertext: wordArray} is incomplete.

So the proper usage is:
```
const encrypted = C.AES.encrypt("Message", "Secret").toString();
// send or store the encryped string.
const decrypted = C.AES.decrypt(encrypted, "Secret").toString(C.enc.Utf8);
```
While:
```
const encrypted = C.AES.encrypt("Message", "Secret").wordArray;
const decrypted = C.AES.decrypt({ciphertext: encrypted}, "Secret").toString(C.enc.Utf8);
```
will get a wrong answer.

**Comment by AlttiRi** [comment]
The reason of the wrong answer is a salt that CryptoJS creates **only when you pass the key as `String`**.
The correct version:
```js
const cipherParams = C.AES.encrypt("Message", "Secret");
const decrypted = C.AES.decrypt({
    ciphertext: cipherParams.ciphertext,
    salt: cipherParams.salt
}, "Secret");
console.log(decrypted2.toString(C.enc.Utf8)); // "Message"
```

Generation the salt for the `String` key is not the related to AES work.

I want to use only AES functional, without "bonus functional".
For that is enough: data `WordArray`, key `WordArray`, iv `WordArray`, padding (optionally) and mode (optionally).
```js
const input = C.lib.WordArray.create([-61338304, 1191554385, -138865087, -290257254], 16);
const key = C.lib.WordArray.create([2045645054, -2029791820, -1952917600, -199318521], 16);
const iv = C.lib.WordArray.create([0, 0, 0, 0], 16);

const ciphertext = C.AES.encrypt(input, key, {
    iv,
    padding: C.pad.NoPadding
}).ciphertext;

const decrypted = C.AES.decrypt({ciphertext}, key,
    {
        iv,
        padding: C.pad.NoPadding
    });
console.log(decrypted); // === input
```

**Comment by entronad** [comment]
I got your point now.
I thought you want to change the type of first param of decode() before.
But in fact you want to say that for the CipherParams class, only ciphertext is requiered and other fields are optional. Right?

**Comment by AlttiRi** [comment]
I think so. 
At least for `decrypt` function only `ciphertext` is required, and `salt` as an optional param, other things will be ignored (`key`, `iv`). 

One more example:
```js
const input = _arrayBufferToWordArray(new TextEncoder().encode("Message"));
const key = C.lib.WordArray.create([2045645054, -2029791820, -1952917600, -199318521], 16);
const iv = C.lib.WordArray.create([1, 2, 3, 4], 16);

const ciphertext = C.AES.encrypt(input, key, {iv}).ciphertext;
const decrypted = C.AES.decrypt({ciphertext}, key, {iv});

console.log(new TextDecoder().decode(_wordArrayToArrayBuffer(decrypted))); // Message
```

This code does not work, although `cipherParams` contains both `key` and `iv`:
```js
const cipherParams = C.AES.encrypt(input, key,{iv});
const decrypted = C.AES.decrypt(cipherParams);
```

**Comment by entronad** [comment]
I have looked into this now.
In fact, CipherParams class has not only fields but some methods: https://github.com/entronad/crypto-es/blob/6f6bd2235f987050a687c0b3e27279ff7d1c6ee4/lib/index.d.ts#L500
That's the main reason of the typescript error. So plain JS objects like `{ciphertext}` will not work even if the fields are set optional.
I suggest the best way is to use a creator or constructor. the params of the creator are quite loose as you need:
```
C.AES.decrypt(C.lib.CipherParams.create({ciphertext}), key, {iv});
or
C.AES.decrypt(new C.lib.CipherParams({ciphertext}), key, {iv});
```

If I change the param of decode() to simply `String | object`, only `C.AES.decrypt({ciphertext}, key, {iv})` will be enough. But I don't think it's a good idea. The reason to use TypeScript is for type safety, we'd better not not to fallback to the plain JS objects, a little bit more codes is nessesary.

**Comment by AlttiRi** [comment]
`index.d.ts` of the original CryptoJS 3.1.2 has 2 types [`CipherParamsData`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3f01799bf2b5632a4a2f6b3b11632bd249d05660/types/cryptojs/index.d.ts#L132-L142)  and [`CipherParams`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3f01799bf2b5632a4a2f6b3b11632bd249d05660/types/cryptojs/index.d.ts#L144-L148).

[`decrypt`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cryptojs/index.d.ts#L193-L194) method accepts especially `CipherParamsData`. You use everywhere `CipherParams`.

In fact I just want to hide IDE warning.

**Comment by AlttiRi** [comment]
By the way

https://github.com/entronad/crypto-es/blob/6f6bd2235f987050a687c0b3e27279ff7d1c6ee4/lib/index.d.ts#L679

The 3rd parametr should be no just `Object`, but [`IBlockCipherCfg`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3f01799bf2b5632a4a2f6b3b11632bd249d05660/types/cryptojs/index.d.ts#L126)
```ts
interface IBlockCipherCfg {
    iv?: WordArray;
    mode?: mode.IBlockCipherModeImpl //default CBC
    padding?: pad.IPaddingImpl //default Pkcs7
}
```

[AES: CryptoJS.lib.ICipherHelper<CryptoJS.lib.IBlockCipherCfg>](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3f01799bf2b5632a4a2f6b3b11632bd249d05660/types/cryptojs/index.d.ts#L435)

**Comment by entronad** [comment]
Well, let me have a thorough think and give this "flexible" param types a good solution.

**Comment by entronad** [comment]
I have added some cfg types: https://github.com/entronad/crypto-es/commit/57f5c48ced90264052fd0c3b201f300b14c57e28
Please upgrade to 1.2.5 and have a try.

**Comment by AlttiRi** [comment]
BTW, when you use Markdown to put code snippet, it's better to specify the language (`js`, `ts`) for color highlighting:
```
   ```js 
```

With:
```js
const hash = CryptoES.MD5("Message");
```
Without:
```
const hash = CryptoES.MD5("Message");
```

It's related to [readme ](https://github.com/entronad/crypto-es/blob/master/README.md)file.

**Comment by jalixdesign** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
DarthVagen, @StevenL2017, @jxpeng98, @RainmanGT, @uncleguanghui, @myywlc, @leapahea, @liulaojian, @threebowrice, @oddwatcher, @nhfmaster, @luckyuncle, @liweidong32768, @codingonion, @liyang85105, @wuyu9527, @iqgnat, @wmil, @kewangnet, @tuangeek, @861130245, @SSymbol, @JiaqiXiang-nb, @tianyikenan, @201708034122, @clientsfromhell, @gooyan, @zhaodc, @zhaozhiqiang, @dragonwong, @h4m5t, @congwang1998, @yichangle0410, @jaykon, @barry800414, @chenshipku, @nickattw, @qiubinglin, @Infi-zc, @wangyiqun1985, @ChatRichAi, @WangJinshans, @magnusguo, @xiaofeng9527, @ianmage, @CodeNeverStops, @lebin, @nerr, @2723070053, @IT-FE-Joshguggle241, @wufish, @Kylo-Cheok, @qpc, @JellyCCQ, @0a00, @sanluku, @abeibei12138, @LianLongBaGua, @Danielw0111, @turboyulin, @liuzhaoming5954, @T110E4, @nishiergouma, @chenyangnb1999, @uuuuuuuuuup, @sivan, @HalloEric, @Arealroookie, @suzhG, @Dear-enjoy, @lyran159, @OliverX2018, @TurkeyTeo, @shrimp0526, @J2oe, @whatever246, @mikamin, @ysj-1992, @JasonZhou404, @lihaoly, @lirunqi, @neptune1225, @Jstarr133, @mattshma, @junyihub, @CrazyDuck827, @joannanananana, @cfcfzzzz, @zh217, @VincentChandelier, @Blingtron4000, @WangMaoyuan, @fsy19960526, @chsiang426, @LogicDancing, @bbbcs, @cooliotseng, @TimothyZero, @MrFirePeakdrgnchan, @Artemisyx, @iamcaojie, @ZaneCode6574, @ouyangyu718, @Elessar123, @Arnult, @Kevin-sa, @mck-dajiao, @Na2O2, @StSamSon0, @umgsai, @xxulin, @Crackajack22, @WWH0928, @12faith23, @NobodyCanStop, @wlinhyriwo, @zhaozihui, @isosky, @chestnutpang, @ZxYuan, @shouyr, @xusi4git, @jianan1104, @Agu168, @olivererwang, @tdss, @alexanderhucheerful, @ximalayashanjiao, @alwaysmavs, @pppshiwen, @tailorcai, @northroom, @xianxiaoyu404, @claudiuszhang, @imxieke, @diobrando-jojo, @0xnomadi, @CN1921, @ytian, @hanzo2020, @sindbad, @YuriChan09, @edt82, @xiaowangzhixiao, @hezhaozhao-git, @iunary, @b51405221, @christian-spooner
