### ISSUE TITLE
TypeError: wordArray.clamp is not a function

### ISSUE THREAD

**Issue by mw108** [entronad/crypto-es#41]
Receiving this error when trying to Base64 encode an encryption result like this:

`const encrypted_content: string = CryptoES.AES.encrypt( content, password ).toString( CryptoES.enc.Base64 );`

It works when I don't pass any formatter to the `toString()` function:

`const encrypted_content: string = CryptoES.AES.encrypt( content, password ).toString();`

The same (unresolved) issue already exists in the CryptoJS library:

https://github.com/brix/crypto-js/issues/189

**Comment by entronad** [comment]
The result of `CryptoES.AES.encrypt( content, password )` is a `CypherParam`, `CypherParam.toString()` only accept a `Format` (CryptoES.format.XXX), `CryptoES.enc.Base64` is an `Encoder` not a `Format`.

You should first get your AES result string and then use `Base64.parse(result)` or `Base64.stringify(reslut)` according to what you need.

**Comment by mw108** [comment]
Ok, thanks for the quick reply and the clarification. 😃

**Comment by Youngemmy5956** [comment]
To address this issue,

const encrypted_content = CryptoES.AES.encrypt(content, password).toString();
const base64Encoded = CryptoES.enc.Base64.stringify(CryptoES.enc.Utf8.parse(encrypted_content));

const base64EncodedCipherText = Buffer.from(cipherText, 'binary').toString('base64');
