### ISSUE TITLE
Distribution for non ES6 environments

### ISSUE THREAD

**Issue by JirkaChadima** [entronad/crypto-es#5]
Hi, this is a great library, however, it is missing an ES2015 compatible distribution on NPM. Are there any plans on adding a transpilation step before publishing this to npm?

Context: We'd like to use this in TS/Angular project that targets ES2015 for compatibility but really cannot, because there is no (easy) way to transpile an external library during the `ng build` process.

**Comment by entronad** [comment]
The original purpose of this library is "a ES6 version of crypto-js", so if you need a ES5 version why not just use crypto-js: https://github.com/brix/crypto-js ?
The cryption result and api of crypto-es is exactly the same as crypto-js

**Comment by JirkaChadima** [comment]
That is probably the path we will take. I was just wondering if there are any plans for es5 transpiled version. Apparently not :)
